CREATE SCHEMA IF NOT EXISTS request_service;

CREATE TABLE IF NOT EXISTS request_service.requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT      NOT NULL,
    event_id     BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT unique_request UNIQUE (requester_id, event_id)
);