CREATE SCHEMA IF NOT EXISTS event_service;

CREATE TABLE IF NOT EXISTS event_service.categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS event_service.events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id       BIGINT        NOT NULL,
    category_id        BIGINT        NOT NULL REFERENCES event_service.categories (id) ON DELETE RESTRICT,
    title              VARCHAR(120)  NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    state              VARCHAR(20)   NOT NULL,
    lat                REAL          NOT NULL,
    lon                REAL          NOT NULL,
    participant_limit  BIGINT        NOT NULL,
    request_moderation BOOLEAN       NOT NULL,
    paid               BOOLEAN       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS event_service.compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS event_service.compilation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id BIGINT NOT NULL REFERENCES event_service.compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES event_service.events(id) ON DELETE CASCADE,
    CONSTRAINT unique_compilation_event UNIQUE (compilation_id, event_id)
);